name: Package and Publish on Master Push

on:
  workflow_dispatch:
    branches:
     # this will change to master once validated
      - initial-deployment
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio pytest-cov flake8 aiohttp
    - name: Lint with Flake8
      run: |
        flake8 qcluster
    - name: Run Tests with Coverage Report
      run: |
        coverage run --source qcluster -m pytest
        coverage report