name: Package and Publish on Master Push

on: workflow_dispatch
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio pytest-cov flake8 aiohttp twine wheel
    - name: Lint with Flake8
      run: |
        flake8 qcluster
    - name: Run Tests with Coverage Report
      run: |
        coverage run --source qcluster -m pytest
        coverage report
    - name: Build on ${{ matrix.python-version }} ${{ matrix.os }}
      run: |
        python setup.py sdist bdist_wheel
    - name: Twine check on ${{ matrix.python-version }} ${{ matrix.os }}
      run: |
        twine check dist/*
    - name: Upload package artifacts
      uses: actions/upload-artifact@v2
      with:
        name: qcluster-pydist
        path: |
          dist

  test_publish:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install twine wheel
      run: |
        python -m pip install --upgrade pip
        pip install twine wheel
    - name: Download build packages
      uses: actions/download-artifact@v2
      with:
          name: qcluster-pydist
          path: artifacts/
    - name: Display structure of downloaded artifacts
      run: ls -R
    - name: Upload to Test PYPI
      env:
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy
        TWINE_USERNAME: __token__
        TWINE_TOKEN: ${{ secrets.QL_TESTPYPI_QCLUSTER }}
      run: |
        twine check .artifacts/*
        twine upload .artifacts/*
